fileConfigs:
  04_outputs.conf: |-
    <label @OUTPUT>
      <match **>
        @type cloudwatch_logs
        log_group_name k8s-lg
        log_stream_name log-stream-name
        auto_create_stream true
        region eu-central-1
      </match>
    </label>

# for more information https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs
plugins:
  - fluent-plugin-cloudwatch-logs
